spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.142:3306/scfp
    username: root
    password: 123
server:
  port: 9898
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.woniuxy.user.entity


