spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
server:
  port: 9898
management:
  endpoints:
    web:
      exposure:
        include: '*'


