spring:
  application:
    name: supply
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
server:
  port: 5858
management:
  endpoints:
    web:
      exposure:
        include: '*'


