spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.142:3306/scfp
    username: root
    password: 1234
    maxActive: 500
    dbcp2: # 进行数据库连接池的配置
      min-idle: 5                                  # 数据库连接池的最小维持连接数
      initial-size: 6                               # 初始化提供的连接数
      max-total: 300                                # 最大的连接数
      max-wait-millis: 60000                # 等待连接获取的最大超时时间

  cloud:
    inetutils: # 忽略虚拟机网卡,避免启动项目时卡顿
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      routes:
        # 流转网络路由
        # 供应链路由
        - id: supply
          uri: lb://supply
          predicates:
            - Path=/supply/**
        # 资金方路由
        - id: bank
          uri: lb://supply
          predicates:
            - Path=/bank/**
        - id: fiance   #路由名
          uri: lb://fiance   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/fiance/**   #匹配的路径|
        - id: fiance   #路由名
          uri: lb://fiance   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/settle/**   #匹配的路径|
        - id: network   #路由名
          uri: lb://supply   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/network/**   #匹配的路径
        # 放款路由
        - id: loan
          uri: lb://loan
          predicates:
            - Path=/loan/**
        # 文件路由
        - id: file
          uri: lb://file
          predicates:
            - Path=/file/**
        # 链单路由
        - id: chain
          uri: http://192.168.8.152:6666
#          uri: lb://chain
          predicates:
            - Path=/chain/**
        # 账户管理
        - id: user
#          uri: http://192.168.8.104:9898/
          uri: lb://user
          predicates:
            - Path=/menu/**

#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true # 服务名小写
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos

server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'    #暴露当前微服务的监控端口，让所有的ip地址都能监控到本微服务
