spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1 #请求的采样率 ：0-1.0

  cloud:
    gateway:
      routes:
        - id: goods   #路由名
          uri: lb://goods   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/goods/**   #匹配的路径
        - id: order   #路由名
          uri: lb://order-feign   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/order/**   #匹配的路径
        - id: auth   #路由名
          uri: lb://auth   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/user/**   #匹配的路径
        - id: kill   #路由名
          uri: lb://kill   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/kill/**   #匹配的路径
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: gateway-8888
