spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: fiance   #路由名
          uri: lb://fiance   #lb:loadbalance   goods:微服务名
        - id: network   #路由名
          uri: lb://supply   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/network/**   #匹配的路径
        - id: order   #路由名
          uri: lb://order-feign   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/fiance/**   #匹配的路径
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'    #暴露当前微服务的监控端口，让所有的ip地址都能监控到本微服务
