spring:
  application:
    name: gateway
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.142:3306/scfp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
  cloud:
    gateway:
      routes:
        - id: network   #路由名
          uri: lb://supply   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/network/**   #匹配的路径
        - id: order   #路由名
          uri: lb://order-feign   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/order/**   #匹配的路径
        - id: auth   #路由名
          uri: lb://auth   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/user/**   #匹配的路径
        - id: kill   #路由名
          uri: lb://kill   #lb:loadbalance   goods:微服务名
          predicates: #谓词
            - Path=/kill/**   #匹配的路径
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
server:
  port: 8888
management:
  endpoints:
    web:
      exposure:
        include: '*'    #暴露当前微服务的监控端口，让所有的ip地址都能监控到本微服务
