spring:
  application:
    name: fiance
  cloud:
    inetutils: # 忽略虚拟机网卡,避免启动项目时卡顿
      ignored-interfaces: 'VMware Virtual Ethernet Adapter for VMnet1,VMware Virtual Ethernet Adapter for VMnet8'
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.8.142:3306/scfp?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123
server:
  port: 4299
management:
  endpoints:
    web:
      exposure:
        include: '*'
mybatis:
  mapper-locations: classpath:/mapper/*.xml
logging:
  level:
    com.woniuxy.fiance.mapper: debug


