spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.142:8848
        username: nacos
        password: nacos
  redis:
    host: localhost
    port: 6379
server:
  port: 10086
management:
  endpoints:
    web:
      exposure:
        include: '*'


