spring:
  application:
    name: auth
  redis:
    host: localhost
    port: 6379
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.8.109:8848
        username: nacos
        password: nacos
server:
  port: 10087
management:
  endpoints:
    web:
      exposure:
        include: '*'    #暴露当前微服务的监控端口，让所有的ip地址都能监控到本微服务